version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: hknews
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

server:
  depends_on:
    - mongo
  build:
    context: ./backend
    dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app

client:
  depends_on:
    - server
  build:
    context: frontend
    dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
