version: "3.8"
services:
  mongo:
    container_name: mongo-hn
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - hackernews

  backend:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile
      target: development
      context: ./backend
    container_name: backend-dev
    restart: always
    ports:
      - 3000:3000
    networks:
      - hackernews
    volumes:
      - ./backend:/backend

  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      target: development
      context: ./frontend
    container_name: frontend-dev
    restart: always
    ports:
      - 5000:5000
    networks:
      - hackernews
    volumes:
      - ./frontend:/frontend

networks:
  hackernews:
    external: true
